services:
  # Serviço principal da API
  - type: web
    name: api-advancemaisv2
    env: node
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/revolcck/api-advancemais
    buildCommand: |
      npm ci
      npx prisma generate
      npm run build
    startCommand: node dist/server.js
    nodeVersion: 18.x
    healthCheckPath: /heltz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REDIS_ENABLED
        value: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_NAME
        value: api-advancemais
      - key: APP_URL
        fromService:
          name: api-advancemaisv2
          type: web
          property: url
      - key: ALLOWED_ORIGINS
        value: "*"
        # Em produção, você deve especificar os domínios permitidos separados por vírgula
        # value: "https://seu-frontend.com,https://outro-dominio.com"
      - key: FRONTEND_URL
        value: "https://seu-frontend.com"
        # Substitua pelo URL real do seu frontend
      - key: DATABASE_URL
        sync: false
        # Esta variável deve ser configurada manualmente no dashboard do Render
        # Formato: mysql://usuariod:senha@host:3306/banco_de_dados
      - key: DATABASE_POOL_MIN
        value: 2
      - key: DATABASE_POOL_MAX
        value: 5
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_STANDARD_HEADERS
        value: true
      - key: RATE_LIMIT_LEGACY_HEADERS
        value: false
      - key: LOG_FORMAT
        value: combined
      - key: LOG_DIR
        value: logs
      - key: LOG_LEVEL
        value: info
      - key: CSRF_PROTECTION
        value: true
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: JWT_ISSUER
        value: api-projeto
      - key: JWT_AUDIENCE
        value: api-clients
      # As variáveis a seguir devem ser configuradas de acordo com sua configuração específica
      # Brevo API (Adicione suas próprias chaves)
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: BREVO_SMS_SENDER
        sync: false
      # MercadoPago (Adicione suas próprias chaves)
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PROD_ENABLED
        value: false
