services:
  # API principal
  - type: web
    name: api-advancemais
    env: node
    plan: starter
    buildCommand: node scripts/render-deploy.js && npm run build
    startCommand: node dist/server.js
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # Segredo - deve ser configurado manualmente no dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_ENABLED
        value: false # Desativa o Redis por padrão, pode ser reativado se configurado
      - key: REDIS_HOST
        fromService:
          name: redis-advancemais
          type: redis
          property: host
          envVarName: REDIS_HOST # Use o Redis apenas se o serviço estiver configurado
      - key: REDIS_PORT
        fromService:
          name: redis-advancemais
          type: redis
          property: port
          envVarName: REDIS_PORT
      - key: REDIS_PASSWORD
        fromService:
          name: redis-advancemais
          type: redis
          property: password
          envVarName: REDIS_PASSWORD
      # Outras variáveis de ambiente necessárias
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: BREVO_SMS_SENDER
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: APP_NAME
        value: api-projeto
      - key: APP_URL
        value: https://api-advancemais.onrender.com
      - key: FRONTEND_URL
        value: https://app-advancemais.onrender.com
      - key: ALLOWED_ORIGINS
        value: "https://app-advancemais.onrender.com,https://advancemais.com"
    healthCheckPath: /api/heltz
    autoDeploy: true

  # Redis para cache e sessões (opcional - pode ser desabilitado inicialmente)
  - type: redis
    name: redis-advancemais
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
