services:
  # API principal
  - type: web
    name: api-advancemais
    env: node
    plan: starter # Mantendo o plano original
    buildCommand: npm install && node scripts/render-prisma-setup.js && node scripts/build.js
    startCommand: node dist/server.js
    nodeVersion: 18.x # Mantendo a versão original do Node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false # Segredo - deve ser configurado manualmente no dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: REDIS_ENABLED
        value: true
      - key: REDIS_HOST
        fromService:
          name: redis-advancemais
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: redis-advancemais
          type: redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          name: redis-advancemais
          type: redis
          property: password
      # Outras variáveis de ambiente necessárias para Brevo e MercadoPago
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_SENDER_EMAIL
        sync: false
      - key: BREVO_SENDER_NAME
        sync: false
      - key: BREVO_SMS_SENDER
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Redis para cache e sessões
  - type: redis
    name: redis-advancemais
    ipAllowList: # Especifique os IPs permitidos ou use ["0.0.0.0/0"] para todos
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # Mantendo o plano original
